### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ItsIsaacIO** [jexline/exline-furniture#1]
Whenever You Try To Run The Latest Version Of The Mod On A Server, It Crashes When Trying To Run.
![image](https://user-images.githubusercontent.com/75589176/132134724-2012860d-da84-41e3-8e37-b6798f345575.png)

**Comment by jexline** [comment]
For some reason RenderType is not found. I'm not sure why but I will try to fix it. It seems no one can get it to work on a server, and it is always the RenderType class not found.

**Comment by jexline** [comment]
Ok, I think I found the problem. I was trying to call RenderType on the server and client, but should only call on client. Here is the new file. It should work, let me know if it still crashes.
EDIT: I was able to get a server up to test on and it works now.
[https://www.curseforge.com/minecraft/mc-mods/exlines-furniture/files/3456936](https://www.curseforge.com/minecraft/mc-mods/exlines-furniture/files/3456936)
