### ISSUE TITLE
Bugged texture

### ISSUE THREAD

**Issue by Jayerd** [jexline/exline-furniture#11]
![image](https://user-images.githubusercontent.com/98251669/150667930-51d730cd-6dc7-4827-ae42-90f38f7ac16b.png)

I dont know how to report properly I'm so sorry if this is wrong or incomplete but the texture is bugged and I don't know if this is the only one. In my inventory its texture is ok but when I place it it's like that. just wanted to let you know <33 tysm

**Comment by Jayerd** [comment]
![image](https://user-images.githubusercontent.com/98251669/150668107-0e665d4b-7864-490f-85be-929bcdc64849.png)

this one too apparently

**Comment by jexline** [comment]
Thank you for reporting this issue! I have fixed the issue as of v2.0.4.
