### ISSUE TITLE
Recipe ID spruce_chair_purple_recipe incorrect, unknown item oak_bird_house

### ISSUE THREAD

**Issue by BreadBxsket** [jexline/exline-furniture#12]
Warnings found through KubeJS
![image](https://user-images.githubusercontent.com/30668741/156242162-1e632fc4-fbf2-485b-95d2-77e75e94baba.png)

W is defined as minecraft:light_purple, should be minecraft:purple_carpet
![image](https://user-images.githubusercontent.com/30668741/156242230-86929d4a-6e29-45f7-aaf4-d15780648e02.png)

**Comment by itsdinkd** [comment]
this... would not be the cause of the mod, but instead the person who created that KubeJS Script.

**Comment by jexline** [comment]
no that was my fault, i put in light purple on accident instead of purple_carpet
