### ISSUE TITLE
stick recipes

### ISSUE THREAD

**Issue by xanthian** [jexline/exline-furniture#14]
my mod (variant sticks and stuff) has variant stick recipes for each wood type. (2 of the same plank)
when exline-furniture is installed only my oak stick works, are you doing anything with stick recipes that could cause this?
as your code is not public i cant begin to look as to where/why this is occurring.
(https://github.com/xanthian/variant_sticks_and_stuff/issues/3)

**Comment by xanthian** [comment]
(https://github.com/xanthian/variant_sticks_and_stuff/issues/3)

**Comment by xanthian** [comment]
anyone active here?

**Comment by jexline** [comment]
Sorry I have not been updating in a while, things have not been great, but getting better.

**Comment by jexline** [comment]
So for the recipes I use the item stick not a tag and this is probably causing the other sticks not to work. I might not add this feature now but maybe in the future. sorry.
