### ISSUE TITLE
Chinese localization file is empty

### ISSUE THREAD

**Issue by KuroPeach** [jexline/exline-furniture#17]
Chinese localization file is empty, Please keep at least {}
![image](https://user-images.githubusercontent.com/19620848/171982706-f21fc30f-2640-4c4a-b184-3eccdf7c3b6b.png)
![image](https://user-images.githubusercontent.com/19620848/171982717-ab9984e8-f3cd-4cb2-9b3f-08928ca9a31e.png)

**Comment by jexline** [comment]
Something strange happened and other lang files are empty as well. They had been completed, yet now are blank and I have no idea why. I will fix this soon, sorry about this.

**Comment by KuroPeach** [comment]
:)
