### ISSUE TITLE
ColorHandlerEvent error with latest version of Forge.

### ISSUE THREAD

**Issue by Gamemassa** [jexline/exline-furniture#20]
MC Version - 1.19
Forge Version - 41.0.85
Mod Version - 2.1.0

Hi,

I tried launching Minecraft with the latest versions of Forge and your Furniture Mod and I got a ColorHandlerEvent error. I've attached the crash report here.

[crash-2022-07-09_17.13.36-fml.txt](https://github.com/jexline/exline-furniture/files/9077938/crash-2022-07-09_17.13.36-fml.txt)

**Comment by jexline** [comment]
Thank you! I made this with an older version of Forge so let me try downloading the new version and see if I can fix this.

**Comment by Gamemassa** [comment]
Just FYI, your More Carpets v1.0.3 mod is also causing crashes.

[crash-2022-07-09_19.15.52-fml.txt](https://github.com/jexline/exline-furniture/files/9078052/crash-2022-07-09_19.15.52-fml.txt)
.

**Comment by jexline** [comment]
It seems like they changed the class, ColorHandlerEvent, to RegisterColorHandlersEvent. I've uploaded the new file to Curseforge or you can join my discord to download now. Thank you for letting me know of this issue!

**Comment by Gamemassa** [comment]
I can confirm, the latest version you uploaded is working perfectly. Once again, thanks so much for the rapid response and friendly support!
