### ISSUE TITLE
Errors in recipes and loot tables

### ISSUE THREAD

**Issue by kohanis** [jexline/exline-furniture#3]
Latest version for 1.18
[log.txt](https://github.com/jexline/exline-furniture/files/7654814/log.txt)

**Comment by jexline** [comment]
Ok, I have fixed the typos in the recipes and removed the other one. Sorry about that, I had left some recipes and loot_tables for some items I am planning on adding to the next update and forgot to remove them. Thank you for pointing this out! I have fixed this issue for Fabric versions 1.18 and 1.17.1, as well as Forge 1.18.

**Comment by ChiefArug** [comment]
This happens on 1.16 too, any plans to copy the fix back to there? Its very annoying when trying to read log files as each wrong recipe prints 60 lines to the log, which stacks up a lot.
