### ISSUE TITLE
Crash on startup 1.17.1

### ISSUE THREAD

**Issue by AlisterGontineac** [jexline/exline-furniture#4]
[Log.txt](https://github.com/jexline/exline-furniture/files/7681854/Log.txt)
[Crash.txt](https://github.com/jexline/exline-furniture/files/7681855/Crash.txt)

" Exline's Furnitire - [Fabric] [1.17.1] " Just crashes on launch. The one from 4 days ago.

**Comment by jexline** [comment]
I found this in the Log.txt, it might be this that is causing the issue, I do not think it is the Furniture mod as I have been able to start up my game solo and on a server just fine, minus some missing recipes i found, but that will not crash the game. Let me know if this mod is the issue and we can close this :)

`[21:50:05] [main/ERROR]: Mixin prepare for mod koi failed preparing ExampleMixin in modid.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found`

**Comment by AlisterGontineac** [comment]
Yep, your assertions are correct, koi seems to be the issue.
